version: '3.3'
services:

#WEBSHOP 2
  postgres-webshop-2:
    image: postgres:12
    restart: always
    volumes:
      - db_data_web_shop_2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine-web-shop-2:
    image: fedormelexin/graphql-engine-arm64:v2.1.0-beta.2
    ports:
      - '8082:8080'
    depends_on:
      - 'postgres-webshop-2'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres-webshop-2:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin-secret
      HASURA_GRAPHQL_ACCESS_KEY: admin-secret  
#FRONT:
  web_shop_2_front:
    build: 
      context: .
      dockerfile: ./Dockerfile.webshop2front
    ports:
      - '3001:3001'
    environment:
      REACT_APP_HGE_ENDPOINT: http://graphql-engine-web-shop-2:8080
      SKIP_PREFLIGHT_CHECK: true
      PORT: 3001
      REACT_APP_PSP_API_KEY: 7b273382-9ac1-4728-8489-2b93b6f59fae
#ACTIONS 
  web_shop_2_actions:
    build: 
      context: .
      dockerfile: ./Dockerfile.webshop2actions
    ports:
      - '3389:3389'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

    environment:
      PORT: 3389
      HASURA_ADMIN_SECRET_HEADER_NAME: x-hasura-admin-secret
      HGE_ADMIN_SECRET: admin-secret
      HGE_ENDPOINT: http://graphql-engine-web-shop-2:8080
      TOKEN_KEY: somerandompasswordsomerandompasswordsomerandompassword
      PSP_ENDPOINT: http://host.docker.internal:8080
      PSP_API_KEY: 7b273382-9ac1-4728-8489-2b93b6f59fae
      PSP_API_SECRET: b5c81921-db55-45f8-817e-ac91cbd08200
      PSP_KEY_HEADER: X-Hasura-PSP_API_KEY
      PSP_SECRET_HEADER: X-Hasura-PSP_SECRET

volumes:
  db_data_web_shop_2:
