version: '3.3'
services:

#WEBSHOP 2
  postgres-webshop-2:
    image: postgres:12
    restart: always
    volumes:
      - db_data_web_shop_2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine-web-shop-2:
    image: hasura/graphql-engine:v2.0.0-alpha.11
    depends_on:
      - 'postgres-webshop-2'
    volumes:
      - type: bind
        source: ./certificates/cert.crt
        target: /etc/ssl/certs/selfsigned.crt
        read_only: true
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres-webshop-2:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin-secret
      HASURA_GRAPHQL_ACCESS_KEY: admin-secret  
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ANONYMOUS
      HASURA_GRAPHQL_JWT_SECRET: "{
        \"type\":\"HS256\",
        \"key\": \"somerandompasswordsomerandompasswordsomerandompassword\",
        \"claims_format\": \"stringified_json\"}"
      ACTION_BASE_ENDPOINT: http://web_shop_2_actions:3389
      ACTION_SECRET: action-secret
      EVENT_SECRET: event-secret
#FRONT:
  # web_shop_2_front:
  #   image: ws2f
  #   restart: always
  #   volumes:
  #     - type: bind
  #       source: .
  #       target: /app
  #       read_only: false
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile.webshop2front
  #   environment:
  #     REACT_APP_HGE_ENDPOINT: https://192.168.43.74:8082
  #     SKIP_PREFLIGHT_CHECK: 'true'
  #     PORT: 3002
  #     REACT_APP_PSP_API_KEY: 7b273382-9ac1-4728-8489-2b93b6f59fae
  #     NODE_TLS_REJECT_UNAUTHORIZED: "0" 

#ACTIONS 
  web_shop_2_actions:
    image: ws2a
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: false
    build: 
      context: .
      dockerfile: ./Dockerfile.webshop2actions

    extra_hosts:
      - 'host.docker.internal:host-gateway'

    environment:
      PORT: 3389
      HASURA_ADMIN_SECRET_HEADER_NAME: x-hasura-admin-secret
      HGE_ADMIN_SECRET: admin-secret
      HGE_ENDPOINT: https://reverseproxy-ws2:8082
      TOKEN_KEY: somerandompasswordsomerandompasswordsomerandompassword
      PSP_ENDPOINT: https://192.168.43.234:8080
      PSP_API_KEY: 9710d4e2-a56c-41c5-a3a2-239857078ce1
      PSP_API_SECRET: be76c7a9-6f75-4622-ab93-f00d0c7b1622
      PSP_KEY_HEADER: X-Hasura-PSP_API_KEY
      PSP_SECRET_HEADER: X-Hasura-PSP_SECRET
      NODE_TLS_REJECT_UNAUTHORIZED: "0" 
      API_KEY_WAGE: 75ba3303-0653-4af8-8708-08446f5b3a04
      API_SECRET_WAGE: e496a166-f223-40de-b336-6580531be741

 
  reverseproxy-ws2:
      image: rvpws2
      restart: always
      build:
        context: .
        dockerfile: ./Dockerfile.ws2.nginx
      ports:
          - 8082:8082
          - 3389:3389
          - 3002:3002

volumes:
  db_data_web_shop_2:
