-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."payment_providers" add column "subscription" boolean
--  not null default 'false';
